# CartPole-v1
OpenAI GYM exercise  
Description:
        A pole is attached by an un-actuated joint to a cart, which moves along a frictionless track. The pendulum starts upright, and the goal is to prevent it from falling over by increasing and reducing the cart's velocity.
        
Reward:
        Reward is 1 for every step taken, including the termination step
    Starting State:
        All observations are assigned a uniform random value in [-0.05..0.05]

Episode Termination:
        Pole Angle is more than 12 degrees
        Cart Position is more than 2.4 (center of the cart reaches the edge of the display)
        Episode length is greater than 200
        Solved Requirements
        Considered solved when the average reward is greater than or equal to 195.0 over 100 consecutive trials.

In [2]:
import gym

In [3]:
env = gym.make('CartPole-v0')

### Understanding `Spaces`

`action_space`, `observation_space`  
These attributes are of type Space, and they describe the format of valid actions and observations

In [5]:
print(env.action_space)    #fixed range, non-negative (0,1,2,...)

Discrete(2)


In [6]:
print(env.observation_space)   #n-dimensional box, array of 4 numbers

Box(4,)


In [7]:
# print the Box's bounds
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


https://medium.com/@tuzzer/cart-pole-balancing-with-q-learning-b54c6068d947
The Cart-Pole world consists of a cart that moves along the horizontal axis and a pole that is anchored on the cart. At every time step, you can observe its position (x), velocity (x_dot), angle (theta), and angular velocity (theta_dot). These are the observable states of this world. At any state, the cart only has two possible actions: move to the left or move to the right.

In other words, the state-space of the Cart-Pole has four dimensions of continuous values and the action-space has one dimension of two discrete values.



    Observation: 
        Type: Box(4)
        Num	Observation                 Min         Max
        0	Cart Position             -4.8            4.8
        1	Cart Velocity             -Inf            Inf
        2	Pole Angle                 -24 deg        24 deg
        3	Pole Velocity At Tip      -Inf            Inf
        
    Actions:
        Type: Discrete(2)
        Num	Action
        0	Push cart to the left
        1	Push cart to the right

### Random move

In [1]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(500):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

/Users/Kevin/anaconda3/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [9]:
env = gym.make('CartPole-v0')

In [2]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(200):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print(f'Episode finished after {t+1}')
            break
env.close()

[ 0.00269475 -0.0071762  -0.04861497  0.00275908]
[ 0.00255123 -0.20156845 -0.04855979  0.27971578]
[-0.00148014 -0.39596526 -0.04296547  0.55669631]
[-0.00939945 -0.59045852 -0.03183155  0.83553898]
[-0.02120862 -0.39491653 -0.01512077  0.5330177 ]
[-0.02910695 -0.19958522 -0.00446042  0.23560889]
[-0.03309865 -0.00439983  0.00025176 -0.05847765]
[-0.03318665  0.19071852 -0.00091779 -0.35108113]
[-0.02937228  0.38585351 -0.00793941 -0.64405333]
[-0.02165521  0.1908431  -0.02082048 -0.3538811 ]
[-0.01783835  0.38625482 -0.0278981  -0.65305593]
[-0.01011325  0.58175393 -0.04095922 -0.95439145]
[ 0.00152183  0.77740224 -0.06004705 -1.25965644]
[ 0.01706987  0.58309769 -0.08524018 -0.98636812]
[ 0.02873183  0.38921431 -0.10496754 -0.72162924]
[ 0.03651611  0.19568893 -0.11940012 -0.46374274]
[ 0.04042989  0.00243877 -0.12867498 -0.21095161]
[ 0.04047867 -0.19063105 -0.13289401  0.03853276]
[ 0.03666604  0.00612148 -0.13212336 -0.2929497 ]
[ 0.03678847 -0.18689352 -0.13798235 -0.04468191]


## Trial Solution

In [7]:
import numpy as np
# Init arbitary values
q_tables = np.zeros([env.observation_space.n, env.action_space.n])

AttributeError: 'Box' object has no attribute 'n'

In [8]:
env.observation_space.n

AttributeError: 'Box' object has no attribute 'n'